"""empty message

Revision ID: 1cff9fb82780
Revises: 
Create Date: 2022-05-24 15:14:35.869607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cff9fb82780'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.add_column('Artist', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('state', sa.String(length=120), nullable=True))
    op.drop_constraint('Artist_city_id_fkey', 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'city_id')
    op.add_column('Venue', sa.Column('city', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('state', sa.String(length=120), nullable=True))
    op.drop_constraint('Venue_city_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'city_id')
    op.drop_table('Cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Venue_city_id_fkey', 'Venue', 'Cities', ['city_id'], ['id'])
    op.drop_column('Venue', 'state')
    op.drop_column('Venue', 'city')
    op.add_column('Artist', sa.Column('city_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Artist_city_id_fkey', 'Artist', 'Cities', ['city_id'], ['id'])
    op.drop_column('Artist', 'state')
    op.drop_column('Artist', 'city')
    op.create_table('Cities',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Cities_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Cities_pkey')
    )
    # ### end Alembic commands ###
